apiVersion: v1
kind: Service
metadata:
  name: marina-weather-app
  labels:
    app: marina
spec:
  type: NodePort
  ports:
    - port: 5000
      targetPort: 5000
  selector:
    app: marina
  externalIPs:
  - 192.168.9.30
